# Generated by Django 4.2.4 on 2023-11-16 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='date_of',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date1', models.DateField(auto_now=True)),
                ('date2', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
